BootStrap: docker
From: ubuntu:22.04

%setup


%files
    # copying files from the host system to the container.
    togovar-convert.rb /usr/local/bin
    togovar-accession.rb /usr/local/bin
    lib/*rb /usr/local/bin/lib/
		
%environment
    export RUBYOPT='-EUTF-8'

%labels
    Maintainer Bioinformation and DDBJ Center
    Version    v1.2


%runscript



%post
    echo "Hello from inside the container"
    sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list
    sed -i.bak -e "s%http://security.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list
    export DEBIAN_FRONTEND="noninteractive"
    apt -y update
    apt -y upgrade
    apt -y install locales
    locale-gen en_US.UTF-8
    update-locale
    apt -y install build-essential autoconf automake wget git zlib1g-dev libbz2-dev libncurses5-dev curl unzip liblzma-dev libcurl4-openssl-dev software-properties-common apt-transport-https libyaml-dev libffi-dev libssl-dev libreadline-dev software-properties-common python2-dev libxml2-utils
    cd /usr/local/src
    wget https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
    tar xzf ruby-3.2.2.tar.gz
    cd ruby-3.2.2
    ./configure
    make
    make install
    gem install csv -v "3.2.3"
    gem install fileutils -v "1.4.1"
    gem install optparse -v "0.2.0"
    gem install json -v "2.6.2"
    gem install pp -v "0.1.0"
    gem install date -v "3.0.0"
    gem install roo -v "2.8.3"
    gem install jsonl -v "0.1.5"
    gem install builder -v "3.2.4"    
    gem install open3 -v "0.1.2"    
    gem install nokogiri -v "1.15.3"    
    gem install net-http -v "0.3.2"    

    cd /usr/local/src
    wget https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2
    tar -xvf samtools-1.10.tar.bz2
    cd samtools-1.10
    ./configure --prefix=/usr/local
    make
    make install
    cd ..
    rm -rf samtools-1.10 samtools-1.10.tar.bz2
    chmod +x /usr/local/bin/*.rb
    chmod +x /usr/local/bin/lib/*.rb
		
		mkdir -p /opt/togovar
		cd /opt/togovar
		wget https://raw.githubusercontent.com/ddbj/pub/master/docs/togovar-repository/xsd/dbVar.xsd
		cd ../..
